config/routes.rb
Rails.application.routes.draw do 
  resources :orders
  resources :category_services
  resources :services
  resources :executors
  get 'home/index' 
  
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category_service.rb
class CategoryService < ApplicationRecord
  has_many :services, dependent: :destroy
end

app/models/executor.rb
class Executor < ApplicationRecord
  has_many :orders, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :executor
  has_and_belongs_to_many :services

end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :category_service
  has_and_belongs_to_many :orders

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/category_services_controller.rb
class CategoryServicesController < ApplicationController
  before_action :set_category_service, only: %i[ show edit update destroy ]

  def index
    @category_services = CategoryService.all
  end

  def show
  end

  def new
    @category_service = CategoryService.new
  end

  def edit
  end

  def create
    @category_service = CategoryService.new(category_service_params)

    respond_to do |format|
      if @category_service.save
        format.html { redirect_to category_service_url(@category_service), notice: "Category service was successfully created." }
        format.json { render :show, status: :created, location: @category_service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category_service.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category_service.update(category_service_params)
        format.html { redirect_to category_service_url(@category_service), notice: "Category service was successfully updated." }
        format.json { render :show, status: :ok, location: @category_service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category_service.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category_service.destroy

    respond_to do |format|
      format.html { redirect_to category_services_url, notice: "Category service was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_category_service
      @category_service = CategoryService.find(params[:id])
    end

    def category_service_params
      params.fetch(:category_service).permit(:name)
    end
end

app/controllers/executors_controller.rb
class ExecutorsController < ApplicationController
  before_action :set_executor, only: %i[ show edit update destroy ]

  def index
    @executors = Executor.all
  end

  def show
  end

  def new
    @executor = Executor.new
  end

  def edit
  end

  def create
    @executor = Executor.new(executor_params)

    respond_to do |format|
      if @executor.save
        format.html { redirect_to executor_url(@executor), notice: "Executor was successfully created." }
        format.json { render :show, status: :created, location: @executor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @executor.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @executor.update(executor_params)
        format.html { redirect_to executor_url(@executor), notice: "Executor was successfully updated." }
        format.json { render :show, status: :ok, location: @executor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @executor.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @executor.destroy

    respond_to do |format|
      format.html { redirect_to executors_url, notice: "Executor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_executor
      @executor = Executor.find(params[:id])
    end

    def executor_params
      params.fetch(:executor).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  def index
    if params[:column] != "service"
      @orders = Order.order("#{params[:column]} #{params[:direction]}")
      @orders = @orders.where('client_name ilike ?', "%#{params[:client_name]}%") if params[:client_name].present?
    elsif params[:column] == "service"
      @orders = Order.all.sort_by{|order| order.services.first.title}
    else
      @orders = Order.all
    end

    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="test.xlsx"'
      }
    end
  end

  def show
  end

  def new
    @order = Order.new
  end

  def edit
  end

  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        flash[:alert] = @order.errors.first.full_message
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.fetch(:order).permit(:client_name, :order_date, :executor_id, service_ids: [])
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[ show edit update destroy ]

  def index
    @services = Service.all
  end

  def show
  end

  def new
    @service = Service.new
  end

  def edit
  end

  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to service_url(@service), notice: "Service was successfully created." }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to service_url(@service), notice: "Service was successfully updated." }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @service.destroy

    respond_to do |format|
      format.html { redirect_to services_url, notice: "Service was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_service
      @service = Service.find(params[:id])
    end

    def service_params
      params.fetch(:service).permit(:title, :category_service_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def sort_link(column:, label:)
    if column == params[:column]
      link_to(label, orders_path(column: column, direction: next_direction))
    else
      link_to(label, orders_path(column: column, direction: 'asc'))
    end
  end
  
  def next_direction
    params[:direction] == 'asc' ? 'desc' : 'asc'
  end
end

app/views/category_services/_category_service.html.erb
<div id="<%= dom_id category_service %>">
  <% if action_name != "show" %>
    <%= link_to "Show this category service", category_service, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this category service', edit_category_service_path(category_service), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/category_services/_form.html.erb
<div class="pb-28 max-w-7xl mx-auto sm:px-6 lg:px-8">
  <div class="bg-white p-8 shadow-md rounded-md text-left">
    <%= form_with(model: category_service) do |form| %>

      <div class="mb-4">
        <%= form.label :name, "Name", class: 'inline-block mb-2 text-gray-700' %><span class="text-red-500">*</span><br>
        <%= form.text_field :name, class: 'block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none'%>
      </div>

      <div class="flex justify-end mt-5">
        <% if current_page?(controller: :category_services, action: :new) %>
          <%= link_to 'Back', category_services_path, style: 'color:black', class: 'inline-flex items-center justify-center px-4 py-2 text-base font-medium leading-6 text-gray-600 whitespace-no-wrap bg-white border border-gray-200 rounded-md shadow-sm hover:bg-gray-50 focus:outline-none focus:shadow-none' %>
        <% elsif current_page?(controller: :category_services, action: :edit) %>
          <%= link_to 'Back', category_service_path, style: 'color:black', class: 'inline-flex items-center justify-center px-4 py-2 text-base font-medium leading-6 text-gray-600 whitespace-no-wrap bg-white border border-gray-200 rounded-md shadow-sm hover:bg-gray-50 focus:outline-none focus:shadow-none' %>
        <% end %>        
        <%= form.submit "Save", class: "ml-2 inline-flex items-center justify-center px-4 py-2 text-base font-medium leading-6 text-white whitespace-no-wrap bg-blue-600 border border-blue-700 rounded-md shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
      </div>

    <% end %>
  </div>
</div>

app/views/category_services/edit.html.erb
<h1 class="py-5 text-gray-900 font-extrabold text-xl md:text-3xl text-center">Editing category</h1>
<%= render 'form', category_service: @category_service %>

app/views/category_services/index.html.erb
<% if @category_services.any? %>
  <div class="max-w-screen-xl mx-auto mb-96">
    <div class="justify-between items-center flex py-5">
      <p class="text-xl text-gray-900">Category</p>
      <%= link_to "New category", new_category_service_path, class: 'ml-2 inline-flex items-center justify-center px-4 py-2 text-base font-medium leading-6 text-white whitespace-no-wrap bg-blue-600 border border-blue-700 rounded-md shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500' %>
    </div>
    <table class="table w-full table-fixed">
      <thead>
        <th class="text-gray-900 bg-gray-400">Name</th>
      </thead>
    </table>
    <div id="categorys">
      <% @category_services.each do |category_service| %>
        <%= link_to category_service, action: 'go' do %>        
          <div class="max-w-screen-xl mx-auto">
            <table class="table w-full table-fixed">
              <tbody>
                <tr class="hover hover:bg-gray-300">
                  <th class="text-gray-900 bg-gray-200"><%= category_service.name %></th>
                </tr>
              </tbody>
            </table>
          </div>
        <% end %> 
      <% end %>
    </div>
  </div>
<% else %>
  <div class="w-full text-center py-8">
    <h1 class="text-gray-900 font-extrabold text-5xl md:text-4xl">Categories</h1>
    <p class="text-gray-500 text-2xl md:text-xl font-normal my-10">No Categories</p>
    <%= link_to "New Category", new_category_service_path, class: 'inline-flex items-center justify-center px-4 py-2 text-base font-medium leading-6 text-white whitespace-no-wrap bg-blue-600 border border-blue-700 rounded-md shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500' %>
  </div>
<% end %>

app/views/category_services/new.html.erb
<h1 class="py-5 text-gray-900 font-extrabold text-xl md:text-3xl text-center">New category</h1>
<%= render 'form', category_service: @category_service %>

app/views/category_services/show.html.erb
<div class="py-5 text-gray-900">
  <%= link_to 'Edit this category', edit_category_service_path(@category_service), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to 'Destroy this category', category_service_path(@category_service), method: :delete, data: { confirm: 'Are you sure?' }, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
  </div>
  <%= link_to 'Back to category', category_services_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>
<div class="p-10 bg-white rounded-lg">
  <div class="gap-6 border-t border-gray-300">
    <div class="grid grid-cols-3 items-center border-b py-5 border-gray-300">
      <label for="name" class="block text-lg font-medium text-gray-900">name</label>
      <span class="col-span-2 bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg block w-full p-3">
        <%= @category_service.name %>
      </span>
    </div>
  </div>
</div>

app/views/executors/_form.html.erb
<div class="pb-28 max-w-7xl mx-auto sm:px-6 lg:px-8">
  <div class="bg-white p-8 shadow-md rounded-md text-left">
    <%= form_with(model: executor) do |form| %>

      <div class="mb-4">
        <%= form.label :name, "Name", class: 'inline-block mb-2 text-gray-700' %><span class="text-red-500">*</span><br>
        <%= form.text_field :name, class: 'block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none'%>
      </div>

      <div class="flex justify-end mt-5">
        <% if current_page?(controller: :executors, action: :new) %>
          <%= link_to 'Back', executors_path, style: 'color:black', class: 'inline-flex items-center justify-center px-4 py-2 text-base font-medium leading-6 text-gray-600 whitespace-no-wrap bg-white border border-gray-200 rounded-md shadow-sm hover:bg-gray-50 focus:outline-none focus:shadow-none' %>
        <% elsif current_page?(controller: :executors, action: :edit) %>
          <%= link_to 'Back', executor_path, style: 'color:black', class: 'inline-flex items-center justify-center px-4 py-2 text-base font-medium leading-6 text-gray-600 whitespace-no-wrap bg-white border border-gray-200 rounded-md shadow-sm hover:bg-gray-50 focus:outline-none focus:shadow-none' %>
        <% end %>        
        <%= form.submit "Save", class: "ml-2 inline-flex items-center justify-center px-4 py-2 text-base font-medium leading-6 text-white whitespace-no-wrap bg-blue-600 border border-blue-700 rounded-md shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
      </div>

    <% end %>
  </div>
</div>

app/views/executors/edit.html.erb
<h1 class="py-5 text-gray-900 font-extrabold text-xl md:text-3xl text-center">Editing executor</h1>
<%= render 'form', executor: @executor %>

app/views/executors/new.html.erb
<h1 class="py-5 text-gray-900 font-extrabold text-xl md:text-3xl text-center">New executor</h1>
<%= render 'form', executor: @executor %>

app/views/executors/show.html.erb
<div class="py-5 text-gray-900">
  <%= link_to 'Edit this executor', edit_executor_path(@executor), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this executor', executor_path(@executor), method: :delete, data: { confirm: 'Are you sure?' }, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to executors', executors_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

<div class="p-10 bg-white rounded-lg">
  <div class="gap-6 border-t border-gray-300">

    <div class="grid grid-cols-3 items-center border-b py-5 border-gray-300">
      <label for="name" class="block text-lg font-medium text-gray-900">name</label>
      <span class="col-span-2 bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg block w-full p-3">
        <%= @executor.name %>
      </span>
    </div>

  </div>
</div>

app/views/home/index.html.erb
Home

app/views/layouts/_header.html.erb
<section class="relative w-full px-8 text-gray-700 bg-white body-font">
  <div class="container flex flex-col flex-wrap items-center justify-between py-5 mx-auto md:flex-row max-w-7xl">
    <%= link_to root_path, class: "relative z-10 flex items-center w-auto text-2xl font-extrabold leading-none text-black select-none" do %>
      <span class="block uppercase">car service.</span>
    <% end %>

    <nav class="top-0 left-0 z-0 flex items-center justify-center w-full h-full py-5 -ml-0 space-x-5 text-base md:-ml-5 md:py-0 md:absolute">
      <%= link_to root_path, class: "relative font-medium leading-6 text-gray-600 transition duration-150 ease-out hover:text-gray-900", role: 'menuitem' do %>
        <span class="block">Home</span>
        <span class="absolute bottom-0 left-0 inline-block w-full h-0.5 -mb-1 overflow-hidden">
          <span x-show="hover" class="absolute inset-0 inline-block w-full h-1 h-full transform bg-gray-900" x-transition:enter="transition ease duration-200" x-transition:enter-start="scale-0" x-transition:enter-end="scale-100" x-transition:leave="transition ease-out duration-300" x-transition:leave-start="scale-100" x-transition:leave-end="scale-0"></span>
        </span>
      <% end %>
      <%= link_to executors_path, class: "relative font-medium leading-6 text-gray-600 transition duration-150 ease-out hover:text-gray-900", role: 'menuitem' do %>
        <span class="block">Executors</span>
        <span class="absolute bottom-0 left-0 inline-block w-full h-0.5 -mb-1 overflow-hidden">
          <span x-show="hover" class="absolute inset-0 inline-block w-full h-1 h-full transform bg-gray-900" x-transition:enter="transition ease duration-200" x-transition:enter-start="scale-0" x-transition:enter-end="scale-100" x-transition:leave="transition ease-out duration-300" x-transition:leave-start="scale-100" x-transition:leave-end="scale-0"></span>
        </span>
      <% end %>
      <%= link_to orders_path, class: "relative font-medium leading-6 text-gray-600 transition duration-150 ease-out hover:text-gray-900", role: 'menuitem' do %>
        <span class="block">Orders</span>
        <span class="absolute bottom-0 left-0 inline-block w-full h-0.5 -mb-1 overflow-hidden">
          <span x-show="hover" class="absolute inset-0 inline-block w-full h-1 h-full transform bg-gray-900" x-transition:enter="transition ease duration-200" x-transition:enter-start="scale-0" x-transition:enter-end="scale-100" x-transition:leave="transition ease-out duration-300" x-transition:leave-start="scale-100" x-transition:leave-end="scale-0"></span>
        </span>
      <% end %>
      <%= link_to services_path, class: "relative font-medium leading-6 text-gray-600 transition duration-150 ease-out hover:text-gray-900", role: 'menuitem' do %>
        <span class="block">Services</span>
        <span class="absolute bottom-0 left-0 inline-block w-full h-0.5 -mb-1 overflow-hidden">
          <span x-show="hover" class="absolute inset-0 inline-block w-full h-1 h-full transform bg-gray-900" x-transition:enter="transition ease duration-200" x-transition:enter-start="scale-0" x-transition:enter-end="scale-100" x-transition:leave="transition ease-out duration-300" x-transition:leave-start="scale-100" x-transition:leave-end="scale-0"></span>
        </span>
      <% end %>
      <%= link_to category_services_path, class: "relative font-medium leading-6 text-gray-600 transition duration-150 ease-out hover:text-gray-900", role: 'menuitem' do %>
        <span class="block">Categories</span>
        <span class="absolute bottom-0 left-0 inline-block w-full h-0.5 -mb-1 overflow-hidden">
          <span x-show="hover" class="absolute inset-0 inline-block w-full h-1 h-full transform bg-gray-900" x-transition:enter="transition ease duration-200" x-transition:enter-start="scale-0" x-transition:enter-end="scale-100" x-transition:leave="transition ease-out duration-300" x-transition:leave-start="scale-100" x-transition:leave-end="scale-0"></span>
        </span>
      <% end %>
    </nav>

    <div class="relative z-10 inline-flex items-center space-x-3 md:ml-5 lg:justify-end">
      <a href="#" class="inline-flex items-center justify-center px-4 py-2 text-base font-medium leading-6 text-gray-600 whitespace-no-wrap bg-white border border-gray-200 rounded-md shadow-sm hover:bg-gray-50 focus:outline-none focus:shadow-none">
        Sign in
      </a>
      <span class="inline-flex rounded-md shadow-sm">
        <a href="#" class="inline-flex items-center justify-center px-4 py-2 text-base font-medium leading-6 text-white whitespace-no-wrap bg-blue-600 border border-blue-700 rounded-md shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
          Sign up
        </a>
      </span>
    </div>
    
  </div>
</section>

<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
<script defer="" src="https://unpkg.com/@lottiefiles/lottie-player@0.4.0/dist/lottie-player.js"></script>
<div at-magnifier-wrapper=""><div class="at-theme-light"><div class="at-base notranslate" translate="no"><div class="Z1-AJ" style="top: 0px; left: 0px;"></div></div></div></div></body>

app/views/orders/edit.html.erb
<h1 class="py-5 text-gray-900 font-extrabold text-xl md:text-3xl text-center">Editing order</h1>
<%= render 'form', order: @order %>

app/views/orders/new.html.erb
<h1 class="py-5 text-gray-900 font-extrabold text-xl md:text-3xl text-center">New order</h1>
<%= render 'form', order: @order %>

app/views/orders/show.html.erb
<div class="py-5 text-gray-900">
  <%= link_to 'Edit this order', edit_order_path(@order), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this order', order_path(@order), method: :delete, data: { confirm: 'Are you sure?' }, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to orders', orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

<div class="p-10 bg-white rounded-lg">
  <div class="gap-6 border-t border-gray-300">

    <div class="grid grid-cols-3 items-center border-b py-5 border-gray-300">
      <label for="client_name" class="block text-lg font-medium text-gray-900">Client name</label>
      <span class="col-span-2 bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg block w-full p-3">
        <%= @order.client_name %>
      </span>
    </div>

    <div class="grid grid-cols-3 items-center border-b py-5 border-gray-300">
      <label for="order_date" class="block text-lg font-medium text-gray-900">Order date</label>
      <span class="col-span-2 bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg block w-full p-3">
        <%= @order.order_date.strftime("%Y-%m-%d") %>
      </span>
    </div>

    <div class="grid grid-cols-3 items-center border-b py-5 border-gray-300">
      <label for="order_date" class="block text-lg font-medium text-gray-900">Executor</label>
      <span class="col-span-2 bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg block w-full p-3">
        <%= @order.executor.name %>
      </span>
    </div>

    <div class="grid grid-cols-3 items-center border-b py-5 border-gray-300">
      <label for="order_date" class="block text-lg font-medium text-gray-900">services</label>
      <span class="col-span-2 bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg block w-full p-3">
       <% @order.services.each do |order| %>
          <%= order.title %>
        <% end %>
      </span>
    </div>

  </div>
</div>

app/views/services/_form.html.erb
<div class="pb-28 max-w-7xl mx-auto sm:px-6 lg:px-8">
  <div class="bg-white p-8 shadow-md rounded-md text-left">
    <%= form_with(model: service) do |form| %>

      <div class="mb-4">
        <%= form.label :title, "Title", class: 'inline-block mb-2 text-gray-700' %><span class="text-red-500">*</span><br>
        <%= form.text_field :title, class: 'block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none'%>
      </div>

       <div class="mb-4">
        <%= form.label :category_service_id, "category", class: 'inline-block mb-2 text-gray-700' %><span class="text-red-500">*</span><br>
        <%= form.collection_select :category_service_id, CategoryService.all, :id, :name, {}, class: 'block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none' %>
      </div>

      <div class="flex justify-end mt-5">
        <% if current_page?(controller: :services, action: :new) %>
          <%= link_to 'Back', services_path, style: 'color:black', class: 'inline-flex items-center justify-center px-4 py-2 text-base font-medium leading-6 text-gray-600 whitespace-no-wrap bg-white border border-gray-200 rounded-md shadow-sm hover:bg-gray-50 focus:outline-none focus:shadow-none' %>
        <% elsif current_page?(controller: :services, action: :edit) %>
          <%= link_to 'Back', service_path, style: 'color:black', class: 'inline-flex items-center justify-center px-4 py-2 text-base font-medium leading-6 text-gray-600 whitespace-no-wrap bg-white border border-gray-200 rounded-md shadow-sm hover:bg-gray-50 focus:outline-none focus:shadow-none' %>
        <% end %>        
        <%= form.submit "Save", class: "ml-2 inline-flex items-center justify-center px-4 py-2 text-base font-medium leading-6 text-white whitespace-no-wrap bg-blue-600 border border-blue-700 rounded-md shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
      </div>

    <% end %>
  </div>
</div>

app/views/services/show.html.erb
<div class="py-5 text-gray-900">
  <%= link_to 'Edit this service', edit_service_path(@service), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this service', service_path(@service), method: :delete, data: { confirm: 'Are you sure?' }, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to service', services_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

<div class="p-10 bg-white rounded-lg">
  <div class="gap-6 border-t border-gray-300">

    <div class="grid grid-cols-3 items-center border-b py-5 border-gray-300">
      <label for="title" class="block text-lg font-medium text-gray-900">title</label>
      <span class="col-span-2 bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg block w-full p-3">
        <%= @service.title %>
      </span>
    </div>

    <div class="grid grid-cols-3 items-center border-b py-5 border-gray-300">
      <label for="title" class="block text-lg font-medium text-gray-900">Category</label>
      <span class="col-span-2 bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg block w-full p-3">
        <%= @service.category_service.name %>
      </span>
    </div>

  </div>
</div>